Volunteer data update app
dev-a-better-world/vacgaps pull request #42
Opened 2021-01-14 15:07 UTC by gilm123

2021-01-18 12:35 UTC, gilm123 commented on tsconfig.base.json
> +    ],
```suggestion
```

2021-01-18 15:02 UTC, idigra requested changes

2021-01-18 15:02 UTC, idigra commented on apps/vaccines-updates-client/src/components/main-form/index.tsx
> +const Container = styled.div`
Can't we pluck it to a scss file?
(If not, at least let's separate it to a tsx file which contains only styling).

2021-01-18 15:02 UTC, idigra commented on apps/vaccines-updates-client/src/components/main-form/parts/city/index.tsx
> +const dropDownOptions = Object.entries(CITIES).map(_ => ({
Sync with main - CITIES dictionary structure has been changed.

2021-01-18 15:02 UTC, idigra commented on apps/vaccines-updates-client/src/components/main-form/parts/target-groups/index.tsx
> +const TargetGroupsContainer = styled.div`
Same as above, let's separate styling to another file.

2021-01-18 15:02 UTC, idigra commented on apps/vaccines-updates-client/src/components/main-form/parts/working-hours/index.tsx
> +            <h3>שעות פעילות</h3>
I don't remember, have we decided what we do with the startTime/endTime issue?
(The issue is that we need a DateTime to indicate the end of spare availability, so if it's not today we know it, and also to not show uncleaned old reports. The structure of hours:minutes doesn't provide it. Also, I think that startTime and endTime of the branch might appear as part of the branch details and not as a standalone property.

2021-01-18 15:02 UTC, idigra commented on libs/constants/src/lib/health-care-services.ts
> +export enum HEALTH_CARE_SERVICE {
Such changes require verifying the report app to work, and also to verify data correction when working against the live data (where healthcare services are still indicated with "0", "1", etc.).

2021-01-20 18:10 UTC, gilm123 commented on apps/vaccines-updates-client/src/components/main-form/parts/city/index.tsx
> +const dropDownOptions = Object.entries(CITIES).map(_ => ({
its a common practice in react, especially when using styled-components

2021-01-20 18:13 UTC, idigra requested changes

2021-01-20 18:13 UTC, idigra commented on apps/vaccines-updates-client/src/providers/FormDataProvider.tsx
> +    endingTime: number;
It's endTime in the contract that is in the FE side (live it like that for now, as the JSON is already aligned to it).

2021-01-23 18:33 UTC, idigra requested changes

2021-01-23 18:33 UTC, idigra commented on libs/constants/src/lib/targetGroups.ts
> +};
Notice all those warnings appear in the PR view in github, e.g. in this file:
![image](https://user-images.githubusercontent.com/42169023/105229279-5c6a5480-5b6c-11eb-9bd2-33eb1dc3e3b3.png)

2021-01-23 18:33 UTC, idigra commented on apps/vaccines-updates-client/src/app/app.spec.tsx
> +    // expect(getByText('Welcome to vaccines-reporter!')).toBeTruthy();
Clean?

2021-01-23 18:33 UTC, idigra commented on apps/vaccines-updates-client/src/components/main-form/index.tsx
> +const Container = styled.div`
Talked offline, this is React's standard.

2021-01-23 18:33 UTC, idigra commented on apps/vaccines-updates-client/src/providers/FormDataProvider.tsx
> +    healthCareService: string;
Merge with VaccinesReport.

2021-01-30 10:04 UTC, merged